### ISSUE TITLE
Create layout drafts

### ISSUE THREAD

**Issue by TitanNano** [TitanNano/MYQuizSupervisor#1]
Please create mock-ups for the supervisor app.

**Comment by TitanNano** [comment]
latest draft by @ai-tm:
![guikonzept_admin_v2 0](https://cloud.githubusercontent.com/assets/15248915/21997660/bfff218e-dc30-11e6-96c1-46f285ea2384.png)

**Comment by ai-mt** [comment]
here is the zip-file for our updated admin GUI:

[GUIKonzept_Admin_V3.1.zip](https://github.com/TitanNano/MYQuizSupervisor/files/711020/GUIKonzept_Admin_V3.1.zip)

**Comment by ai-mt** [comment]
Here is the updated admin GUI

![guikonzept_admin_v3 2](https://cloud.githubusercontent.com/assets/15248915/22100143/8a9c3fea-de2e-11e6-8a84-ba01ca9e9e76.png)

**Comment by TitanNano** [comment]
1. navigation is not requied
2. main page: reduce this page to, "write a new question" and "send a predefined question"
3. "send predefined question" is to complicated. try to reduce the selection of the question or question list into one single UI element.
4. also move the comboBox for group selection to the top. 
5. room field is not required. groups and rooms are the same.
6. it must be possible to select a person from the list of people for that group
7. "write new question", please simplify the creation of answers, too many buttons.
8. "question pool" is obsolete
9. "Group Mask" is not required. Groups can't be edited or created inside the supervisor.

**Comment by msproje** [comment]
Here is the updated admin GUI

![admin](https://cloud.githubusercontent.com/assets/15341883/22106221/fb11d6e0-de47-11e6-93a0-b818caaefb17.png)

**Comment by msproje** [comment]
Here is the updated admin GUI

<img width="1692" alt="admin" src="https://cloud.githubusercontent.com/assets/15341883/22108489/b91890b0-de53-11e6-9c67-f538aa1f1205.png">

**Comment by TitanNano** [comment]
**Mobile Supervisor**

- Login wird benötitgt, einfaches vordefiniertes Passwort
- **Neue Maske: Veranstaltung Erstellen**
    - Textbox für Name der Veranstaltung
    - Bei bestätigung weiterleitung auf Fragebogen Maske wo die neu erstellte Veranstaltung schon ausgewählt ist
- **Maske: Frage(bogen) senden**
    - Zeitlimit muss einstellbar sein, Format mm:ss
    - Liste der Fragen wird nur angezeigt, kein -/+ Button
    - Aktuelles Gruppen-Dropdown wird Veranstaltungs-Dropdown
        - PIN in Klammern hinter dem Namen
    - Schema:
        - Veranstaltung
        - Gruppe
        - Fragen
        - Zeit
    - ~~Beim Bestätigen wird eine PIN angezeigt die der Supervisor mündlich ausgibt~~
- **Neue Maske Frage Starten:**
    - Dropdown mit Personen aus der Gruppe die auf Maske “Fragebogen senden”
    - Erste Person in der Liste Standardmäßig ausgewählt
    - Ein “Start” Knopf und ein Timer der auf der Fragebogen senden Maske eingestellt wurde
    - Während Timer läuft ist Dropdown nicht veränderbar, Startbutton gesperrt
    - Anschließend wird nächste Person der Liste automatisch ausgewählt
- Maske: Frage erstellen
     - Gruppenauswahl ist jetzt Veranstaltungsauswahl
     - Keine Personenliste
     - Zeitlimit muss einstellbar sein, Format mm:ss
     - Senden statt speichern button
     - Die App soll ein “Gedächtnis” haben. Gewählte Einstellungen in Dropdowns etc sollen so eingestellt bleiben

**Comment by msproje** [comment]
<img width="1039" alt="mockups_admin" src="https://cloud.githubusercontent.com/assets/15341883/22247419/033589ac-e23a-11e6-818e-9b947682f9a4.png">
